### ISSUE TITLE
Look into e2e tests for SD

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#133]
we need e2e for SD , lets start with k8s as this is the most popular one and should be easiest to implement.

we can add some metrics in Prometheus for
 - Total endpoints
 - Total num of updates

Should run a job and compare expected vs actual target count and meta info. It would be better to compare against some set expected results instead of another Prometheus version(because if both versions are broken than we won't catch any bugs.)

**Comment by krasi-georgiev** [comment]
to catch bugs like

https://github.com/prometheus/prometheus/issues/3664
https://github.com/prometheus/prometheus/issues/4124

**Comment by geekodour** [comment]
@sipian @krasi-georgiev 
Since the different SD mechanisms will require setting up their own SD setup. Is there any way to run these SD mechanisms(other than filesd and staticsd) with the current prombench setup with GKE? or will have to follow a different approach.

```
azure_sd_config
consul_sd_config
dns_sd_config
ec2_sd_config
openstack_sd_config
file_sd_config
gce_sd_config
kubernetes_sd_config
marathon_sd_config
nerve_sd_config
serverset_sd_config
triton_sd_config
```

can you explain a bit on how adding new metrics to prometheus will aid this?
> we can add some metrics in Prometheus for
> - Total endpoints
> - Total num of updates

Once the SD mechanisms the are working, I guess the following can be done easily with the http api
> compare expected vs actual target count and meta info



Also, how do you suggest we decide which metrics to look for. For eg. with https://github.com/prometheus/prometheus/issues/4498 it was `process_open_fsd` , just comparing the targets and meta info would not catch https://github.com/prometheus/prometheus/issues/4498 I suppose.

**Comment by krasi-georgiev** [comment]
@simonpasquier 	mentioned that might be looking into these so probably can give some ideas.

**Comment by simonpasquier** [comment]
@geekodour happy to provide more information! I think that we can already improve the testing coverage by adding more tests directly to the prometheus project itself. For instance, we could run an instance of Consul in the CI and check the Consul SD acts accordingly. The same could be done for DNS, Zookeeper (Nerve + ServerSet) and maybe OpenStack and Marathon. Azure, EC2 and GCE are more problematic...

For the metrics, a few have been added since this issue was filed: `prometheus_sd_discovered_targets`, `prometheus_sd_updates_total`, `prometheus_sd_updates_delayed_total` and `prometheus_sd_received_updates_total`. Not sure if we need more right now.

Re catching bugs, we can't come up with all the possible causes of breakage and they often manifest for setups that would be hard to replicate (eg lots of targets, lots of jobs, ...) so I wouldn't think too hard about it.
