### ISSUE TITLE
Usage of python scalar in loadgen unclear

### ISSUE THREAD

**Issue by geekodour** [prometheus/test-infra#178]
So I was looking at [6_loadgen.yaml](https://github.com/prometheus/prombench/blob/master/components/prombench/manifests/benchmark/6_loadgen.yaml) and I am unclear about the usage of the python scalar.

There's a [python scalar](https://github.com/prometheus/prombench/blob/master/cmd/load-generator/main.py#L25) and there's the [go scalar](https://github.com/prometheus/prombench/tree/master/cmd/scaler). The python scalar is not used in `6_loadgen.yaml` but the python querier is used. So the python scalar is redundant and should be removed?

Secondly I think there's no Makefile for pushing [`cmd/load-generator/Dockerfile`](https://github.com/prometheus/prombench/blob/master/cmd/load-generator/Dockerfile) , the Docker file for: https://hub.docker.com/r/prombench/load-generator .

cc @krasi-georgiev  @sipian

**Comment by sipian** [comment]
The python scaler was replaced with the client scaler in https://github.com/prometheus/prombench/pull/139.

At that time it was discussed to leave python scaler as it is. Don't remember the reason though 😛.
I think we can remove it now as it causes unnecessary confusion as stated above.

For the loadgen Makefile , since we didn't have a CI to push docker images, I guess we had left it like that.

We'll have a CI soon after
https://github.com/prometheus/prombench/pull/177  is merged.

**Comment by geekodour** [comment]
great! I'll add the changes then.
