### ISSUE TITLE
[Prombench] Read template values from environment variables by default.

### ISSUE THREAD

**Issue by nevill** [prometheus/test-infra#344]
Usually, we call `prombench` with a dozen of variables like 
`./prombench gke resource apply -v ZONE:$ZONE -v PROJECT_ID:$PROJECT_ID -v CLUSTER_NAME:$CLUSTER_NAME -v PR_NUMBER:$PR_NUMBER -v GITHUB_TOKEN:$GITHUB_TOKEN -v GITHUB_REPO:$GITHUB_REPO ...`.
The values are actually from environment variables.
It's better to read from the environment variables directly.

**Comment by krasi-georgiev** [comment]
I think it is fine as it is because explicit cli arg are much better to reason and you don't have to look at the source code.

@bwplotka did a very good blogpost recently which is related.
https://www.bwplotka.dev/2020/flagarize/

**Comment by nevill** [comment]
It's not the same case as `flagarize` or `kingpin` trying to solve. In @bwplotka 's example, we can easily list all the arguments required by `--help`. But in `prombench` case, these `-v` variables are from templates, not from the `prombench` program itself. Meaning, they can be added or removed from time to time. Certainly, we can keep the ability to overwrite them from cli args.

So, it's NOT explicit in `prombench`, this is the key.

In fact, I wanted to suggest that having an arg like `./prombench -e` to list all the variables used in the templates, but I find out that a `grep '{{ .VariableName }}' *.yml` is enough somehow.

**Comment by krasi-georgiev** [comment]
Yeah I was pointing out that using cli args is more explicit. Another argument I would have against is that usually when you start mixing ways to configure things it soon becomes a mess. Anyway, I will leave it to you and @geekodour to decide :)

**Comment by geekodour** [comment]
I think it's fine because `-v` are just the template variables and different manifest files need different template variables. Having the ability to just pass text to `-v` is also handy. 

> I wanted to suggest that having an arg like `./prombench -e`

If we keep explicit `-v` flags, `prombench` anyway complains about missing variables. (we can improve on the error message though), also agree with @krasi-georgiev on not having to look at the manifest file just to find out what are the variables being used. 

The command itself also acts as some kind of documentation on how to run that manifest file, otherwise one has to look into the manifestfile and then set the required env vars.

Please let me know what you think about keeping these variables explicit, @nevill .

**Comment by bwplotka** [comment]
Keep in mind that we probably should use flags first and only fallback to config / env if really necessary.


Is this necessary now? Why? Can we use CLI flags? :hugs:

**Comment by nevill** [comment]
I agree that we have to make these `-v` variables explicit. @geekodour All the ways you mentioned to make it explicit is good enough.

But this issue is about reading variables from environment. Because I see there is a duplication to pass the variables around when running it in GH action. I see @krasi-georgiev worried of it becoming a mess, but as long as we only use it for template variables, it will be fine.

**Comment by nevill** [comment]
Right now, I understand that, you may invoke `prombench` by `make resource_apply`, it contains all the variables to be set there in `Makefile`. It can be a solution.
